feat: update systemd to 257.13-1~deb13u1

diff --git a/debian/systemd-resolved.postinst b/debian/systemd-resolved.postinst
--- a/debian/systemd-resolved.postinst
+++ b/debian/systemd-resolved.postinst
@@ -26,18 +26,13 @@ fi
 if [ "$1" = configure ] && dpkg --compare-versions "$2" lt 251.4-2; then
     if [ "$(readlink "${DPKG_ROOT}/etc/resolv.conf")" != "../run/systemd/resolve/stub-resolv.conf" ] && [ "$(readlink "${DPKG_ROOT}/etc/resolv.conf")" != "/run/systemd/resolve/stub-resolv.conf" ]; then
         echo "Converting /etc/resolv.conf to a symlink to /run/systemd/resolve/stub-resolv.conf..."
+        mkdir -p "${DPKG_ROOT}/run/systemd/resolve"
         if [ -f "${DPKG_ROOT}/etc/resolv.conf" ]; then
+            cp "${DPKG_ROOT}/etc/resolv.conf" "${DPKG_ROOT}/run/systemd/resolve/stub-resolv.conf" || echo "Cannot copy /etc/resolv.conf to /run/systemd/resolve/stub-resolv.conf"
             mv "${DPKG_ROOT}/etc/resolv.conf" "${DPKG_ROOT}/etc/.resolv.conf.systemd-resolved.bak" || echo "Cannot take a backup of /etc/resolv.conf."
         fi
         ln -sf ../run/systemd/resolve/stub-resolv.conf "${DPKG_ROOT}/etc/resolv.conf" || echo "Cannot install symlink from /etc/resolv.conf to ../run/systemd/resolve/stub-resolv.conf"
     fi
 fi
-
-# Create the dbus configuration file after the sysuser/passwd operation
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-   systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} systemd-resolve.conf
-fi
-
-touch /usr/share/dbus-1/system.d/org.freedesktop.resolve1.conf || true
 
 #DEBHELPER#
